name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build and push image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: b07209016/grpc-aes
          dockerfile: Dockerfile
          always_pull: true
          tags: ${{ github.ref_name }}
